console.log(typeof "Hello")
console.log(typeof 1)
console.log(typeof 1234545789n)
console.log(typeof Symbol("Hiii"))
console.log(typeof y)
console.log(typeof true)
console.log(typeof null)
console.log(typeof function(){})